version: '3.4'

services:
    users.api:
        image: ${DOCKER_REGISTRY-}usersapi
        build:
            context: .
            dockerfile: Users.Api/Dockerfile

    mariadb:
        image: mariadb:latest
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: P@ssw0rd
